#!/bin/bash
if [ "$1" = "--version" ]; then
  echo "${TARGET}-gcc (GCC) 4.9 20140827 (prerelease)"
  echo "Copyright (C) 2014 Free Software Foundation, Inc."
  echo "This is free software; see the source for copying conditions.  There is NO"
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
else
  exec $thecc "${@/-fno-var-tracking-assignments/}"
  # exec $thecc "$theargs"
fi
